# Generated by Django 5.2.16 on 2026-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmp_cert_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='iso_cert_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_url',
            field=models.URLField(blank=True),
        ),
    ]
