# Generated by Django 5.2.17 on 2026-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excipient',
            name='grade',
            field=models.CharField(blank=True, help_text='e.g. USP, EP, BP, JP', max_length=50),
        ),
    ]
