# Generated by Django 5.2.17 on 2026-08-26 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_excipient_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('qc_hold', 'QC Hold'), ('released', 'Released'), ('quarantined', 'Quarantined'), ('expired', 'Expired'), ('depleted', 'Depleted'), ('recalled', 'Recalled')], default='available', max_length=20)),
                ('coa_url', models.URLField(blank=True)),
                ('sds_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.AddField(
            model_name='excipient',
            name='cas_number',
            field=models.CharField(blank=True, help_text='Chemical Abstracts Service number', max_length=50),
        ),
        migrations.AddField(
            model_name='excipient',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text="e.g. ['GMP','ISO']"),
        ),
        migrations.AddField(
            model_name='excipient',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='excipient',
            name='function',
            field=models.CharField(blank=True, help_text='e.g. Diluent, Binder', max_length=100),
        ),
        migrations.AddField(
            model_name='excipient',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0, help_text='Typical fulfilment lead time'),
        ),
        migrations.AlterField(
            model_name='excipient',
            name='category',
            field=models.CharField(choices=[('Binder', 'Binder'), ('Filler', 'Filler'), ('Lubricant', 'Lubricant'), ('Preservative', 'Preservative'), ('Coating', 'Coating'), ('Solvent', 'Solvent'), ('Disintegrant', 'Disintegrant'), ('API', 'API'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AddIndex(
            model_name='excipient',
            index=models.Index(fields=['cas_number'], name='catalog_exc_cas_num_8e4219_idx'),
        ),
        migrations.AddField(
            model_name='batch',
            name='excipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.excipient'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['excipient'], name='catalog_bat_excipie_6a71a3_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['status'], name='catalog_bat_status_a39003_idx'),
        ),
    ]
