# Generated by Django 5.2.17 on 2026-08-26 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('account_verified', 'Account Verified'), ('supplier_approved', 'Supplier Approved'), ('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('batch_allocated', 'Batch Allocated'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('rfq_received', 'RFQ Received'), ('quote_received', 'Quote Received'), ('document_verified', 'Document Verified'), ('document_expiring', 'Document Expiring'), ('low_stock', 'Low Stock'), ('price_changed', 'Price Changed'), ('dispute_updated', 'Dispute Updated')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email')], default='in_app', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_be3f1a_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_9edb86_idx')],
            },
        ),
    ]
