# Generated by Django 5.2.17 on 2026-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dispute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('supplier_review', 'Supplier Review'), ('confirmed', 'Confirmed'), ('batch_allocated', 'Batch Allocated'), ('qc_release', 'QC Release'), ('preparing', 'Preparing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('buyer_confirmed', 'Buyer Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('disputed', 'Disputed'), ('return_requested', 'Return Requested'), ('recalled', 'Recalled')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
