# Generated by Django 5.2.17 on 2026-08-26 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, max_length=50, unique=True)),
                ('ingredient_name', models.CharField(max_length=255)),
                ('cas_number', models.CharField(blank=True, max_length=50)),
                ('required_grade', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('additional_requirements', models.TextField(blank=True)),
                ('verified_suppliers_only', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('quoted', 'Quoted'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RFQQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('moq', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('validity_days', models.PositiveIntegerField(default=30)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='rfq.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['buyer'], name='rfq_rfq_buyer_i_4105aa_idx'),
        ),
        migrations.AddIndex(
            model_name='rfq',
            index=models.Index(fields=['status'], name='rfq_rfq_status_208c61_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqquote',
            index=models.Index(fields=['rfq'], name='rfq_rfqquot_rfq_id_8bb424_idx'),
        ),
        migrations.AddIndex(
            model_name='rfqquote',
            index=models.Index(fields=['supplier'], name='rfq_rfqquot_supplie_77b158_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfqquote',
            unique_together={('rfq', 'supplier')},
        ),
    ]
