# Generated by Django 6.0.7 on 2026-08-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='logistics.rider'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user'], name='logistics_a_user_id_f1e2fb_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['availability_status'], name='logistics_r_availab_354d10_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['rider'], name='logistics_d_rider_i_ea458a_idx'),
        ),
    ]
