# Generated by Django 5.2.17 on 2026-08-26 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_batch_excipient_cas_number_excipient_certifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('registered', 'Registered'), ('profile_submitted', 'Profile Submitted'), ('documents_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('additional_info', 'Additional Info Required'), ('approved', 'Approved'), ('active', 'Active'), ('rejected', 'Rejected'), ('resubmission', 'Resubmission')], default='registered', max_length=30)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_reviews', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('coa', 'Certificate of Analysis'), ('sds', 'Safety Data Sheet'), ('gmp', 'GMP Certificate'), ('iso', 'ISO Certificate'), ('business_license', 'Business License'), ('manufacturing_license', 'Manufacturing License'), ('tse_bse', 'TSE/BSE Declaration'), ('regulatory_letter', 'Regulatory Letter'), ('allergen', 'Allergen Declaration'), ('halal', 'Halal Certificate'), ('kosher', 'Kosher Certificate'), ('other', 'Other')], max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('replaced', 'Replaced')], default='uploaded', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.batch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.excipient')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'documents',
                'indexes': [models.Index(fields=['status'], name='documents_d_status_07369e_idx'), models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx')],
            },
        ),
    ]
